// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PapaBob.Persistance;

namespace PapaBob.Migrations
{
    [DbContext(typeof(PizzaContext))]
    partial class PizzaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("PapaBob.Persistance.PorucenaPizza", b =>
                {
                    b.Property<int>("PorucenaPizzaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cena")
                        .HasColumnType("REAL");

                    b.Property<string>("Kora")
                        .HasColumnType("TEXT");

                    b.Property<int>("PorudzbinaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Velicina")
                        .HasColumnType("TEXT");

                    b.Property<string>("Zacini")
                        .HasColumnType("TEXT");

                    b.HasKey("PorucenaPizzaId");

                    b.HasIndex("PorudzbinaId");

                    b.ToTable("Pizze");
                });

            modelBuilder.Entity("PapaBob.Persistance.Porudzbina", b =>
                {
                    b.Property<int>("PorudzbinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adressa")
                        .HasColumnType("TEXT");

                    b.Property<double>("Cena")
                        .HasColumnType("REAL");

                    b.Property<string>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<string>("PorucilacIme")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasColumnType("TEXT");

                    b.HasKey("PorudzbinaId");

                    b.ToTable("Porudzbine");
                });

            modelBuilder.Entity("PapaBob.Persistance.PorucenaPizza", b =>
                {
                    b.HasOne("PapaBob.Persistance.Porudzbina", "Porudzbina")
                        .WithMany("Pizze")
                        .HasForeignKey("PorudzbinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
